# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hasAC',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='hasMic',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='hasProjector',
            field=models.BooleanField(default=True),
        ),
    ]
