# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161105212454 on 2017-03-28 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20170316_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.TextField(default=''),
        ),
    ]
