# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161105212454 on 2017-04-06 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20170404_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='expenditure',
            field=models.IntegerField(default=0),
        ),
    ]
