# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Meeting Name', max_length=1000),
            preserve_default=False,
        ),
    ]
