# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161105212454 on 2017-04-06 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170316_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
